DROP TABLE IF EXISTS "TB_BZCB_YJ";
CREATE TABLE "TB_BZCB_YJ" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FDEPTID" varchar(383),
    "FCHARGETYPEID" varchar(383),
    "FCHARGETYPENAME" varchar(383),
    "FAMOUNT" numeric(15,2),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_BZCB_YJ" IS '医技科室收入数据中间表';
COMMENT ON COLUMN "TB_BZCB_YJ"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_YJ"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_BZCB_YJ"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_BZCB_YJ"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_BZCB_YJ"."FDEPTID" IS '执行科室编码';
COMMENT ON COLUMN "TB_BZCB_YJ"."FCHARGETYPEID" IS '收费类别编码';
COMMENT ON COLUMN "TB_BZCB_YJ"."FCHARGETYPENAME" IS '收费类别名称';
COMMENT ON COLUMN "TB_BZCB_YJ"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_BZCB_YJ"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_BZCB_YJ"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_BZCB_YJ"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_BZCB_YJ"."YLYL2" IS '预留二';