DROP TABLE IF EXISTS "TB_KSCB_SR";
CREATE TABLE "TB_KSCB_SR" (
    "YLJGDM" varchar(33),
    "FID" varchar(75),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FSOURCE" varchar(30),
    "FAMOUNT" numeric,
    "FBILLINGDEPTID" varchar(45),
    "FBILLINGDEPTNAME" varchar(75),
    "FEXECDEPTID" varchar(45),
    "FEXECDEPTNAME" varchar(75),
    "FCOSTITEMID" varchar(45),
    "FCOSTITEMNAME" varchar(75),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_KSCB_SR" IS '收入数据类别汇总中间表';
COMMENT ON COLUMN "TB_KSCB_SR"."YLJGDM" IS '医疗机构组代码';
COMMENT ON COLUMN "TB_KSCB_SR"."FID" IS '主键';
COMMENT ON COLUMN "TB_KSCB_SR"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_KSCB_SR"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_KSCB_SR"."FSOURCE" IS '来源类型';
COMMENT ON COLUMN "TB_KSCB_SR"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_KSCB_SR"."FBILLINGDEPTID" IS '开单科室编码';
COMMENT ON COLUMN "TB_KSCB_SR"."FBILLINGDEPTNAME" IS '开单科室名称';
COMMENT ON COLUMN "TB_KSCB_SR"."FEXECDEPTID" IS '执行科室编码';
COMMENT ON COLUMN "TB_KSCB_SR"."FEXECDEPTNAME" IS '执行科室名称';
COMMENT ON COLUMN "TB_KSCB_SR"."FCOSTITEMID" IS '收费项目编码';
COMMENT ON COLUMN "TB_KSCB_SR"."FCOSTITEMNAME" IS '收费项目名称';
COMMENT ON COLUMN "TB_KSCB_SR"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_KSCB_SR"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_KSCB_SR"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_KSCB_SR"."YLYL2" IS '预留二';