DROP TABLE IF EXISTS "TB_XMCB_RYJF";
CREATE TABLE "TB_XMCB_RYJF" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "FSOURCESYS" varchar(30),
    "FDEPT" varchar(30),
    "FDEPTNAME" varchar(75),
    "FCOSTPROJECT" varchar(30),
    "FCOSTPROJECTNAME" varchar(75),
    "FMEDPROJECTID" varchar(30),
    "FMEDPROJECTNAME" varchar(75),
    "FPRICE" numeric(18,8),
    "FQTY" numeric(18,8),
    "FAMOUNT" numeric(18,8),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_XMCB_RYJF" IS '人员经费明细表';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FID" IS '主键';
COMMENT ON COLUMN "TB_XMCB_RYJF"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FSOURCESYS" IS '数据来源';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FDEPT" IS '源系统科室编码';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FDEPTNAME" IS '源系统科室名称';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FCOSTPROJECT" IS '成本项目编码';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FCOSTPROJECTNAME" IS '成本项目名称';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FMEDPROJECTID" IS '来源医疗项目编码';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FMEDPROJECTNAME" IS '来源医疗项目名称';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FPRICE" IS '单价';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FQTY" IS '数量';
COMMENT ON COLUMN "TB_XMCB_RYJF"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_XMCB_RYJF"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_XMCB_RYJF"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_XMCB_RYJF"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_XMCB_RYJF"."YLYL2" IS '预留二';