DROP TABLE IF EXISTS "TB_CIS_CRLYYJL";
CREATE TABLE "TB_CIS_CRLYYJL" (
    "YLJGDM" varchar(33),
    "CRLMXLSH" varchar(96),
    "CRLJLLSH" varchar(96),
    "MZZYBZ" varchar(2),
    "JZLSH" varchar(96),
    "MZZYH" varchar(27),
    "YWMC" varchar(192),
    "YPYF" varchar(48),
    "YYPCDM" varchar(6),
    "YYPCMC" varchar(48),
    "YWJXDM" numeric,
    "YWSYCJL" numeric,
    "SYJLDW" varchar(96),
    "YWSYZJL" numeric,
    "YYTJDM" varchar(6),
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_CRLYYJL" IS '出入量用药记录';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."CRLMXLSH" IS '出入量用药明细流水号';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."CRLJLLSH" IS '出入量记录流水号';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."MZZYBZ" IS '门诊/住院标志';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."MZZYH" IS '门诊/住院号';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YWMC" IS '药物名称';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YPYF" IS '药品用法';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YYPCDM" IS '用药频次代码';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YYPCMC" IS '用药频次名称';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YWJXDM" IS '药物剂型代码';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YWSYCJL" IS '药物使用次剂量';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."SYJLDW" IS '使用剂量单位';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YWSYZJL" IS '药物使用总剂量';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YYTJDM" IS '用药途径代码';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_CRLYYJL"."YLYL2" IS '预留二';