DROP TABLE IF EXISTS "TB_CIS_MZSQFSJL";
CREATE TABLE "TB_CIS_MZSQFSJL" (
    "YLJGDM" varchar(33),
    "MZSQFSJLLSH" varchar(96),
    "MZZYBZ" varchar(2),
    "JZLSH" varchar(96),
    "MZZYH" varchar(27),
    "DZSQDBH" varchar(150),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "SSJBH" varchar(15),
    "TZKG" numeric(9,3),
    "ABOXXDM" varchar(2),
    "RHXXDM" varchar(2),
    "SQZDBM" varchar(750),
    "SQZDMC" varchar(1500),
    "NSSSSJCZBM" varchar(75),
    "NSSSSJCZMC" varchar(120),
    "NSSMZFFDM" varchar(30),
    "NSSMZFFMC" varchar(150),
    "SQHBJB" varchar(150),
    "ZYSX" varchar(1500),
    "JYBS" varchar(150),
    "GMS" varchar(1500),
    "XDTJCJG" varchar(1500),
    "XBXXJCJG" varchar(1500),
    "CTJCJG" varchar(1500),
    "BCJCJG" varchar(1500),
    "MRIJCJG" varchar(1500),
    "FGNJCJG" varchar(1500),
    "XCGJCJG" varchar(1500),
    "NCGJCJG" varchar(1500),
    "NXGNJCJG" varchar(1500),
    "GGNJCJG" varchar(1500),
    "XQFXJCJG" varchar(1500),
    "YBZKJCJG" varchar(1500),
    "JSZTZCBZ" varchar(2),
    "XZTZJG" varchar(1500),
    "FBTZJG" varchar(1500),
    "SZJCJG" varchar(1500),
    "JZJCJG" varchar(1500),
    "FBJCJG" varchar(1500),
    "QGJCJG" varchar(1500),
    "YCJCJG" varchar(1500),
    "SQMZYZ" varchar(1500),
    "MZSYZ" varchar(150),
    "MZYSXM" varchar(108),
    "MZYSGH" varchar(54),
    "MZYSQMRQSJ" timestamp,
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_MZSQFSJL" IS '麻醉术前访视记录';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZSQFSJLLSH" IS '麻醉术前访视记录流水号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZZYBZ" IS '门诊/住院标志';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZZYH" IS '门诊/住院号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."DZSQDBH" IS '电子申请单编号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."SSJBH" IS '手术间编号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."TZKG" IS '体重（kg）';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."ABOXXDM" IS 'ABO血型代码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."RHXXDM" IS 'Rh血型代码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."SQZDBM" IS '术前诊断编码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."SQZDMC" IS '术前诊断名称';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NSSSSJCZBM" IS '拟实施手术及操作编码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NSSSSJCZMC" IS '拟实施手术及操作名称';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NSSMZFFDM" IS '拟实施麻醉方法代码';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NSSMZFFMC" IS '拟实施麻醉方法名称';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."SQHBJB" IS '术前合并疾病';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."ZYSX" IS '注意事项';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."JYBS" IS '简要病史';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."GMS" IS '过敏史';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."XDTJCJG" IS '心电图检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."XBXXJCJG" IS '胸部X线检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."CTJCJG" IS 'CT检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."BCJCJG" IS 'B超检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MRIJCJG" IS 'MRI检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."FGNJCJG" IS '肺功能检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."XCGJCJG" IS '血常规检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NCGJCJG" IS '尿常规检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."NXGNJCJG" IS '凝血功能检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."GGNJCJG" IS '肝功能检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."XQFXJCJG" IS '血气分析检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."YBZKJCJG" IS '一般状况检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."JSZTZCBZ" IS '精神状态正常标志';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."XZTZJG" IS '心脏听诊结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."FBTZJG" IS '肺部听诊结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."SZJCJG" IS '四肢检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."JZJCJG" IS '脊柱检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."FBJCJG" IS '腹部检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."QGJCJG" IS '气管检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."YCJCJG" IS '牙齿检查结果';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."SQMZYZ" IS '术前麻醉医嘱';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZSYZ" IS '麻醉适应证';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZYSXM" IS '麻醉医师姓名';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZYSGH" IS '麻醉医师编号';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."MZYSQMRQSJ" IS '麻醉医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_MZSQFSJL"."YLYL2" IS '预留二';