DROP TABLE IF EXISTS "TB_CIS_HZYSJLB";
CREATE TABLE "TB_CIS_HZYSJLB" (
    "HZYSJLSH" varchar(96),
    "YLJGDM" varchar(33),
    "HZJLLSH" varchar(96),
    "HZRQSJ" timestamp,
    "HZYJ" varchar(3000),
    "PX" numeric,
    "YSGH" varchar(54),
    "YSXM" varchar(108),
    "HZYSKSDM" varchar(54),
    "HZYSKSMC" varchar(108),
    "HZYSJGTYSHXYDM" varchar(54),
    "HZYSJGMC" varchar(108),
    "JLRQSJ" timestamp,
    "JLRGH" varchar(54),
    "JLRXM" varchar(108),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_HZYSJLB" IS '会诊医生记录表';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZYSJLSH" IS '会诊医生记录流水号';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZJLLSH" IS '会诊记录流水号';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZRQSJ" IS '会诊日期时间';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZYJ" IS '会诊意见';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."PX" IS '排序';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."YSGH" IS '医生工号';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."YSXM" IS '医生姓名';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZYSKSDM" IS '会诊医生科室代码';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZYSKSMC" IS '会诊医生科室名称';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZYSJGTYSHXYDM" IS '会诊医生机构代码';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."HZYSJGMC" IS '会诊医生机构名称';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."JLRQSJ" IS '记录日期时间';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."JLRGH" IS '记录人工号';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."JLRXM" IS '记录人姓名';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_HZYSJLB"."YLYL2" IS '预留二';