DROP TABLE IF EXISTS "TB_SXZZ_ZCJLB";
CREATE TABLE "TB_SXZZ_ZCJLB" (
    "YLJGDM" varchar(33),
    "ZCJLID" varchar(54),
    "ZZLSH" varchar(54),
    "ZDJGMC" varchar(108),
    "BRZSY" varchar(96),
    "HZZJHM" varchar(48),
    "HZZJLX" varchar(3),
    "MZZYBZ" varchar(2),
    "JZLSH" varchar(54),
    "MJZH" varchar(54),
    "ZYH" varchar(54),
    "HZXM" varchar(108),
    "HZCSRQ" timestamp,
    "HZXB" varchar(2),
    "JTZZ" varchar(450),
    "LXDH" varchar(21),
    "FZYSGH" varchar(24),
    "FZYSXM" varchar(108),
    "FZKSBM" varchar(30),
    "FZKSMC" varchar(45),
    "CBYX" varchar(1536),
    "ZZYY" varchar(1536),
    "ZYJWS" varchar(1536),
    "ZLJG" varchar(3000),
    "ZZRQSJ" timestamp,
    "ZXYLJGDM" varchar(54),
    "ZXYLJGMC" varchar(108),
    "ZXKSBM" varchar(30),
    "ZXKSMC" varchar(45),
    "ZXYSGH" varchar(24),
    "ZXYSXM" varchar(108),
    "QTYXCL" varchar(1500),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_SXZZ_ZCJLB" IS '转诊（院）转出记录表';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZCJLID" IS '转出记录 ID';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZZLSH" IS '转诊流水号';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZDJGMC" IS '转出机构名称';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."HZZJHM" IS '患者证件号码';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."HZZJLX" IS '患者证件类型';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."MZZYBZ" IS '门诊住院标志';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."MJZH" IS '门(急)诊号';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."HZXM" IS '患者姓名';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."HZCSRQ" IS '患者出生日期';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."HZXB" IS '患者性别';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."JTZZ" IS '家庭住址';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."LXDH" IS '联系电话';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."FZYSGH" IS '负责医生工号';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."FZYSXM" IS '负责医生姓名';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."FZKSBM" IS '负责科室编码';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."FZKSMC" IS '负责科室名称';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."CBYX" IS '初步印象';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZZYY" IS '转诊原因';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZYJWS" IS '主要既往史';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZLJG" IS '治疗经过';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZZRQSJ" IS '转诊时间';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZXYLJGDM" IS '转向医疗机构代码';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZXYLJGMC" IS '转向医疗机构名称';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZXKSBM" IS '转向科室编码';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZXKSMC" IS '转向科室名称';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZXYSGH" IS '转向医生工号';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."ZXYSXM" IS '转向医生姓名';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."QTYXCL" IS '其他医学处置';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_SXZZ_ZCJLB"."YLYL2" IS '预留二';