DROP TABLE IF EXISTS "TB_KSCB_NB";
CREATE TABLE "TB_KSCB_NB" (
    "YLJGDM" varchar(33),
    "FID" varchar(75),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FSOURCE" varchar(30),
    "FDEPTID" varchar(45),
    "FDEPTNAME" varchar(75),
    "FDSTDEPTID" varchar(45),
    "FDSTDEPTNAME" varchar(75),
    "FSERVICEITEMID" varchar(45),
    "FSERVICEITEMNAME" varchar(75),
    "FSERVICEQTY" numeric,
    "FOUTPADTIMES" numeric,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_KSCB_NB" IS '内部服务数据中间表';
COMMENT ON COLUMN "TB_KSCB_NB"."YLJGDM" IS '医疗机构组代码';
COMMENT ON COLUMN "TB_KSCB_NB"."FID" IS '主键';
COMMENT ON COLUMN "TB_KSCB_NB"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_KSCB_NB"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_KSCB_NB"."FSOURCE" IS '来源类型';
COMMENT ON COLUMN "TB_KSCB_NB"."FDEPTID" IS '服务科室编码';
COMMENT ON COLUMN "TB_KSCB_NB"."FDEPTNAME" IS '服务科室名称';
COMMENT ON COLUMN "TB_KSCB_NB"."FDSTDEPTID" IS '被服务科室编码';
COMMENT ON COLUMN "TB_KSCB_NB"."FDSTDEPTNAME" IS '被服务科室名称';
COMMENT ON COLUMN "TB_KSCB_NB"."FSERVICEITEMID" IS '服务项目编码';
COMMENT ON COLUMN "TB_KSCB_NB"."FSERVICEITEMNAME" IS '服务项目名称';
COMMENT ON COLUMN "TB_KSCB_NB"."FSERVICEQTY" IS '服务量';
COMMENT ON COLUMN "TB_KSCB_NB"."FOUTPADTIMES" IS '服务当量';
COMMENT ON COLUMN "TB_KSCB_NB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_KSCB_NB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_KSCB_NB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_KSCB_NB"."YLYL2" IS '预留二';