DROP TABLE IF EXISTS "TB_BZCB_MZ";
CREATE TABLE "TB_BZCB_MZ" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FACCOUNTNO" varchar(75),
    "FOPEFLOWNUMBER" varchar(75),
    "FORDERDEPTID" varchar(383),
    "FEXECUTEDEPTID" varchar(383),
    "FORDERDATE" timestamp,
    "FEXECUTEDATE" timestamp,
    "FAMOUNT" numeric(15,2),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_BZCB_MZ" IS '麻醉收入数据中间表';
COMMENT ON COLUMN "TB_BZCB_MZ"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_MZ"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_BZCB_MZ"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_BZCB_MZ"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_BZCB_MZ"."FACCOUNTNO" IS '住院流水号';
COMMENT ON COLUMN "TB_BZCB_MZ"."FOPEFLOWNUMBER" IS '介入手术流水号';
COMMENT ON COLUMN "TB_BZCB_MZ"."FORDERDEPTID" IS '开单科室编码';
COMMENT ON COLUMN "TB_BZCB_MZ"."FEXECUTEDEPTID" IS '执行科室编码';
COMMENT ON COLUMN "TB_BZCB_MZ"."FORDERDATE" IS '开单日期';
COMMENT ON COLUMN "TB_BZCB_MZ"."FEXECUTEDATE" IS '执行日期';
COMMENT ON COLUMN "TB_BZCB_MZ"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_BZCB_MZ"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_BZCB_MZ"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_BZCB_MZ"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_BZCB_MZ"."YLYL2" IS '预留二';