DROP TABLE IF EXISTS "TB_JC_KSDZB";
CREATE TABLE "TB_JC_KSDZB" (
    "YLJGDM" varchar(33),
    "HISKSDM" varchar(30),
    "HISKSMC" varchar(30),
    "BAKSDM" varchar(30),
    "BAKSMC" varchar(30),
    "CBZXDM" varchar(30),
    "CBZXMC" varchar(30),
    "HSDYDM" varchar(30),
    "HSDYMC" varchar(30),
    "HISKSLX" varchar(15),
    "HISKSNWKBS" varchar(15),
    "HISKSBQBS" varchar(15),
    "TYBS" numeric,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_JC_KSDZB" IS '科室对照表';
COMMENT ON COLUMN "TB_JC_KSDZB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_JC_KSDZB"."HISKSDM" IS 'HIS 科室代码';
COMMENT ON COLUMN "TB_JC_KSDZB"."HISKSMC" IS 'HIS 科室名称';
COMMENT ON COLUMN "TB_JC_KSDZB"."BAKSDM" IS '病案科室代码';
COMMENT ON COLUMN "TB_JC_KSDZB"."BAKSMC" IS '病案科室名称';
COMMENT ON COLUMN "TB_JC_KSDZB"."CBZXDM" IS '成本中心代码';
COMMENT ON COLUMN "TB_JC_KSDZB"."CBZXMC" IS '成本中心名称';
COMMENT ON COLUMN "TB_JC_KSDZB"."HSDYDM" IS '核算单元代码';
COMMENT ON COLUMN "TB_JC_KSDZB"."HSDYMC" IS '核算单元名称';
COMMENT ON COLUMN "TB_JC_KSDZB"."HISKSLX" IS 'HIS 科室类型';
COMMENT ON COLUMN "TB_JC_KSDZB"."HISKSNWKBS" IS 'HIS 科室内外科标识';
COMMENT ON COLUMN "TB_JC_KSDZB"."HISKSBQBS" IS 'HIS 科室病区标识';
COMMENT ON COLUMN "TB_JC_KSDZB"."TYBS" IS '停用标识';
COMMENT ON COLUMN "TB_JC_KSDZB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_JC_KSDZB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_JC_KSDZB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_JC_KSDZB"."YLYL2" IS '预留二';