DROP TABLE IF EXISTS "TB_CIS_SHSCBCJL";
CREATE TABLE "TB_CIS_SHSCBCJL" (
    "YLJGDM" varchar(33),
    "SHBCLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(255),
    "NLH" varchar(48),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "MZFFDM" varchar(30),
    "MZFFMC" varchar(48),
    "SSYSGH" varchar(54),
    "SSYSXM" varchar(108),
    "SJYSGH" varchar(54),
    "SJYSXM" varchar(108),
    "SHZDMC" varchar(1500),
    "SHZDBM" varchar(750),
    "SZZDMC" varchar(1500),
    "SZZDBM" varchar(750),
    "SSMXLSH" varchar(75),
    "ZDYJ" varchar(1500),
    "ZYSX" varchar(1500),
    "YSXM" varchar(108),
    "YSGH" varchar(54),
    "QMRQSJ" timestamp,
    "SSJCZBM" varchar(75),
    "SSJCZMC" varchar(120),
    "SSJCZMBBWM" varchar(75),
    "SSRQSJ" timestamp,
    "SSGC" varchar(3000),
    "SHZYGCSX" varchar(3000),
    "SHCLCS" varchar(3000),
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_SHSCBCJL" IS '术后首次病程记录';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SHBCLSH" IS '术后病程流水号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."MZFFDM" IS '麻醉方法代码';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."MZFFMC" IS '麻醉方法名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSYSGH" IS '手术医生工号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSYSXM" IS '手术医生姓名';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SJYSGH" IS '上级医生工号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SJYSXM" IS '上级医生姓名';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SHZDMC" IS '术后诊断名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SHZDBM" IS '术后诊断编码';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SZZDMC" IS '术中诊断名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SZZDBM" IS '术中诊断编码';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSMXLSH" IS '手术明细流水号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."ZDYJ" IS '诊断依据';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."ZYSX" IS '注意事项';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."YSXM" IS '医师姓名';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."YSGH" IS '医师编号';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."QMRQSJ" IS '签名日期时间';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSJCZBM" IS '手术及操作编码';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSJCZMC" IS '手术及操作名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSJCZMBBWM" IS '手术及操作目标部位名称';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSRQSJ" IS '手术日期时间';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SSGC" IS '手术过程';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SHZYGCSX" IS '术后注意观察事项';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."SHCLCS" IS '术后处理措施';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_SHSCBCJL"."YLYL2" IS '预留二';