DROP TABLE IF EXISTS "TB_SXZZ_HZJLB";
CREATE TABLE "TB_SXZZ_HZJLB" (
    "YLJGDM" varchar(33),
    "HZJLID" varchar(54),
    "ZZLSH" varchar(54),
    "ZCJGMC" varchar(108),
    "BRZSY" varchar(96),
    "HZZJHM" varchar(48),
    "HZZJLX" varchar(3),
    "MZZYBZ" varchar(2),
    "JZLSH" varchar(54),
    "MJZH" varchar(54),
    "ZYH" varchar(54),
    "HZXM" varchar(108),
    "HZCSRQ" timestamp,
    "HZXB" varchar(2),
    "JTZZ" varchar(450),
    "FZYSGH" varchar(24),
    "FZYSXM" varchar(108),
    "FZKSBM" varchar(30),
    "FZKSMC" varchar(45),
    "ZYJCJG" varchar(1536),
    "KFJY" varchar(1536),
    "JHZLFA" varchar(1536),
    "HZSJ" timestamp,
    "ZXYLJGDM" varchar(54),
    "ZXYLJGMC" varchar(108),
    "ZXKSBM" varchar(30),
    "ZXKSMC" varchar(45),
    "ZXYSGH" varchar(24),
    "ZXYSXM" varchar(108),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_SXZZ_HZJLB" IS '转诊（院）回转记录表';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZJLID" IS '回转记录 ID';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZZLSH" IS '转诊流水号';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZCJGMC" IS '转出机构名称';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZZJHM" IS '患者证件号码';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZZJLX" IS '患者证件类型';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."MZZYBZ" IS '门诊住院标志';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."MJZH" IS '门(急)诊号';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZXM" IS '患者姓名';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZCSRQ" IS '患者出生日期';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZXB" IS '患者性别';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."JTZZ" IS '家庭住址';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."FZYSGH" IS '负责医生工号';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."FZYSXM" IS '负责医生姓名';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."FZKSBM" IS '负责科室编码';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."FZKSMC" IS '负责科室名称';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZYJCJG" IS '主要检查结果';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."KFJY" IS '康复建议';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."JHZLFA" IS '今后治疗方案';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."HZSJ" IS '回转时间';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZXYLJGDM" IS '转向医疗机构代码';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZXYLJGMC" IS '转向医疗机构名称';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZXKSBM" IS '转向科室编码';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZXKSMC" IS '转向科室名称';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZXYSGH" IS '转向医生工号';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."ZXYSXM" IS '转向医生姓名';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_SXZZ_HZJLB"."YLYL2" IS '预留二';