DROP TABLE IF EXISTS "TB_CIS_GZHCSYJL";
CREATE TABLE "TB_CIS_GZHCSYJL" (
    "YLJGDM" varchar(33),
    "HCSYJLLSH" varchar(96),
    "BRZSY" varchar(96),
    "NLS" numeric(3,0),
    "NLY" varchar(12),
    "NLH" varchar(48),
    "JZLSH" varchar(96),
    "MZZYBZ" varchar(2),
    "MZZYH" varchar(27),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "JBZDBM" varchar(750),
    "JBZDMC" varchar(1500),
    "ZRXHCBZ" varchar(2),
    "CLMC" varchar(300),
    "CPBM" varchar(30),
    "CPSCCJ" varchar(105),
    "CPGYS" varchar(105),
    "HCDW" varchar(96),
    "SL" numeric(8,0),
    "SYTJ" varchar(45),
    "HSXM" varchar(108),
    "HSGH" varchar(54),
    "QMRQSJ" timestamp,
    "BLSXSJ" timestamp,
    "HCSBM" varchar(192),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_GZHCSYJL" IS '高值耗材使用记录';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."HCSYJLLSH" IS '高值耗材使用记录流水号';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."MZZYBZ" IS '门诊/住院标志';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."MZZYH" IS '门诊/住院号';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."JBZDBM" IS '疾病诊断编码';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."JBZDMC" IS '疾病诊断名称';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."ZRXHCBZ" IS '植入性耗材标志';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."CLMC" IS '材料名称';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."CPBM" IS '产品编码';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."CPSCCJ" IS '产品生产厂家';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."CPGYS" IS '产品供应商';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."HCDW" IS '耗材单位';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."SL" IS '数量';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."SYTJ" IS '使用途径';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."HSXM" IS '护士姓名';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."HSGH" IS '护士编号';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."QMRQSJ" IS '签名日期时间';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."HCSBM" IS '耗材识别码';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_GZHCSYJL"."YLYL2" IS '预留二';