DROP TABLE IF EXISTS "TB_TJ_REGISTER";
CREATE TABLE "TB_TJ_REGISTER" (
    "YLJGDM" varchar(33),
    "TJLSH" varchar(75),
    "TJH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLXS" varchar(48),
    "TJCS" numeric,
    "BRXM" varchar(108),
    "XBDM" varchar(2),
    "XBMC" varchar(30),
    "DJRQ" timestamp,
    "TJLBDM" varchar(2),
    "GZDWMC" varchar(105),
    "ZZBM" varchar(75),
    "ZZMC" varchar(750),
    "TBRQ" timestamp,
    "XGBZ" numeric,
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_TJ_REGISTER" IS '体检登记表';
COMMENT ON COLUMN "TB_TJ_REGISTER"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_TJ_REGISTER"."TJLSH" IS '体检流水号';
COMMENT ON COLUMN "TB_TJ_REGISTER"."TJH" IS '体检编号';
COMMENT ON COLUMN "TB_TJ_REGISTER"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_TJ_REGISTER"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_TJ_REGISTER"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_TJ_REGISTER"."NLXS" IS '年龄（小时）';
COMMENT ON COLUMN "TB_TJ_REGISTER"."TJCS" IS '体检次数';
COMMENT ON COLUMN "TB_TJ_REGISTER"."BRXM" IS '本人姓名';
COMMENT ON COLUMN "TB_TJ_REGISTER"."XBDM" IS '性别代码';
COMMENT ON COLUMN "TB_TJ_REGISTER"."XBMC" IS '性别名称';
COMMENT ON COLUMN "TB_TJ_REGISTER"."DJRQ" IS '登记日期';
COMMENT ON COLUMN "TB_TJ_REGISTER"."TJLBDM" IS '体检类别代码';
COMMENT ON COLUMN "TB_TJ_REGISTER"."GZDWMC" IS '工作单位名称';
COMMENT ON COLUMN "TB_TJ_REGISTER"."ZZBM" IS '症状编码（标准）';
COMMENT ON COLUMN "TB_TJ_REGISTER"."ZZMC" IS '症状名称（标准）';
COMMENT ON COLUMN "TB_TJ_REGISTER"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_TJ_REGISTER"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_TJ_REGISTER"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_TJ_REGISTER"."YLYL2" IS '预留二';