DROP TABLE IF EXISTS "TB_ZY_RYDJMXB";
CREATE TABLE "TB_ZY_RYDJMXB" (
    "YLJGDM" varchar(33),
    "RYJLID" varchar(54),
    "BRZSY" varchar(96),
    "SJJLZT" varchar(2),
    "JZLSH" varchar(54),
    "MZYSGH" varchar(54),
    "MZYSXM" varchar(108),
    "MZYSSFZHM" varchar(27),
    "ZYYSBH" varchar(54),
    "ZYYSXM" varchar(108),
    "ZYYSSFZHM" varchar(27),
    "RYQKDM" varchar(2),
    "RYBQDM" varchar(2),
    "RYTJBM" varchar(3),
    "RYYYBM" varchar(3),
    "ZYYYSJ" timestamp,
    "RYKSBM" varchar(96),
    "RYKSMC" varchar(114),
    "RYSJ" timestamp,
    "RYDJYGH" varchar(54),
    "RYDJYXM" varchar(108),
    "LGBZ" varchar(2),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_ZY_RYDJMXB" IS '入院登记明细表';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYJLID" IS '入院记录 ID';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."SJJLZT" IS '数据记录状态';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."MZYSGH" IS '门诊医师编号';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."MZYSXM" IS '门诊医师姓名';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."MZYSSFZHM" IS '门诊医师身份证号码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."ZYYSBH" IS '住院医师编号';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."ZYYSXM" IS '住院医师姓名';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."ZYYSSFZHM" IS '住院医师身份证号码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYQKDM" IS '入院情况代码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYBQDM" IS '入院病情代码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYTJBM" IS '入院途径编码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYYYBM" IS '入院原因编码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."ZYYYSJ" IS '住院预约时间';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYKSBM" IS '入院科室编码';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYKSMC" IS '入院科室名称';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYSJ" IS '入院时间';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYDJYGH" IS '入院登记员编号';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."RYDJYXM" IS '入院登记员姓名';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."LGBZ" IS '留观标志';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_ZY_RYDJMXB"."YLYL2" IS '预留二';