DROP TABLE IF EXISTS "TB_BZCB_SFXM";
CREATE TABLE "TB_BZCB_SFXM" (
  "FID" varchar(75),
  "YLJGDM" varchar(33),
  "TJND" varchar(6),
  "TJYF" varchar(3),
  "YLJGDM" varchar(33),
  "FID" varchar(54),
  "FACCOUNTNO" varchar(75),
  "FPATIENTNO" varchar(75),
  "FPATIENTNAME" varchar(75),
  "FORDERDEPTID" varchar(383),
  "FEXECDEPTID" varchar(383),
  "FCHARGEITEMID" varchar(383),
  "FCHARGEITEMNAME" varchar(383),
  "FCHARGETYPEID" varchar(383),
  "FCHARGETYPENAME" varchar(383),
  "FORDERDATE" timestamp,
  "FEXECDATE" timestamp,
  "FQTY" numeric(15,2),
  "FPRICE" numeric(15,2),
  "FAMOUNT" numeric(15,2),
  "TBRQ" timestamp,
  "XGBZ" varchar(2),
  "YLYL1" varchar(192),
  "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_BZCB_SFXM" IS '收费项目明细数据中间表';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_SFXM"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_BZCB_SFXM"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_BZCB_SFXM"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_BZCB_SFXM"."YLJGDM" IS '医疗机构组代码';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FACCOUNTNO" IS '住院流水号';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FPATIENTNO" IS '住院号';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FPATIENTNAME" IS '患者姓名';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FORDERDEPTID" IS '开单科室编码';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FEXECDEPTID" IS '执行科室编码';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FCHARGEITEMID" IS '收费项目编码';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FCHARGEITEMNAME" IS '收费项目名称';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FCHARGETYPEID" IS '收费类别编码';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FCHARGETYPENAME" IS '收费类别名称';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FORDERDATE" IS '开单日期';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FEXECDATE" IS '执行日期';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FQTY" IS '数量';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FPRICE" IS '收费单价';
COMMENT ON COLUMN "TB_BZCB_SFXM"."FAMOUNT" IS '收费金额';
COMMENT ON COLUMN "TB_BZCB_SFXM"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_BZCB_SFXM"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_BZCB_SFXM"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_BZCB_SFXM"."YLYL2" IS '预留二';