DROP TABLE IF EXISTS "TB_BZCB_SSSR";
CREATE TABLE "TB_BZCB_SSSR" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FACCOUNTNO" varchar(75),
    "FOPEFLOWNUMBER" varchar(75),
    "FORDERDEPTID" varchar(383),
    "FEXECUTEDEPTID" varchar(383),
    "FORDERDATE" timestamp,
    "FEXECUTEDATE" timestamp,
    "FPATIENTNAME" varchar(75),
    "FAMOUNT" numeric,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_BZCB_SSSR" IS '手术收入数据中间表';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_SSSR"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_BZCB_SSSR"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_BZCB_SSSR"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FACCOUNTNO" IS '住院流水号';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FOPEFLOWNUMBER" IS '手术流水号';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FORDERDEPTID" IS '开单科室编码';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FEXECUTEDEPTID" IS '执行科室编码';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FORDERDATE" IS '开单日期';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FEXECUTEDATE" IS '执行日期';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FPATIENTNAME" IS '患者姓名';
COMMENT ON COLUMN "TB_BZCB_SSSR"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_BZCB_SSSR"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_BZCB_SSSR"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_BZCB_SSSR"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_BZCB_SSSR"."YLYL2" IS '预留二';