DROP TABLE IF EXISTS "TB_XMCB_ZCZJ";
CREATE TABLE "TB_XMCB_ZCZJ" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "FSOURCESYS" varchar(30),
    "FDEPT" varchar(75),
    "FDEPTNAME" varchar(75),
    "FCOSTPROJECT" varchar(30),
    "FCOSTPROJECTNAME" varchar(75),
    "FMEDPROJECTID" varchar(75),
    "FMEDPROJECTNAME" varchar(75),
    "FAMOUNT" numeric(18,8),
    "FTYPE" varchar(30),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_XMCB_ZCZJ" IS '资产折旧明细表';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FID" IS '主键';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FSOURCESYS" IS '数据来源';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FDEPT" IS '源系统科室编码';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FDEPTNAME" IS '源系统科室名称';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FCOSTPROJECT" IS '成本项目编码';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FCOSTPROJECTNAME" IS '成本项目名称';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FMEDPROJECTID" IS '来源医疗项目编码';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FMEDPROJECTNAME" IS '来源医疗项目名称';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."FTYPE" IS '成本项目类别编码';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_XMCB_ZCZJ"."YLYL2" IS '预留二';