DROP TABLE IF EXISTS "TB_ZY_CYDJMXB";
CREATE TABLE "TB_ZY_CYDJMXB" (
    "YLJGDM" varchar(33),
    "CYJLID" varchar(54),
    "BRZSY" varchar(96),
    "SJJLZT" varchar(2),
    "JZLSH" varchar(75),
    "CYKSBM" varchar(96),
    "CYKSMC" varchar(114),
    "ZYYSGH" varchar(54),
    "ZYYSXM" varchar(108),
    "ZYYSSFZHM" varchar(27),
    "SFLCLJ" varchar(2),
    "LCLJLX" varchar(3),
    "CYSJ" timestamp,
    "LCYXLXBM" varchar(3),
    "RYQK" varchar(2),
    "SQSHZDFHQK" varchar(2),
    "MZCYZDFHQK" varchar(2),
    "RYCYZDFHQK" varchar(2),
    "FSBLZDFHQK" varchar(2),
    "BLJCLCZDFHQK" varchar(2),
    "YYGRQK" varchar(2),
    "GRBW" varchar(150),
    "YYGRMC" varchar(150),
    "QJCS" numeric,
    "QJCGCS" numeric,
    "LGBZ" varchar(2),
    "BXLX" varchar(30),
    "TXBZ" varchar(2),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_ZY_CYDJMXB" IS '出院登记明细表';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."CYJLID" IS '出院记录 ID';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."SJJLZT" IS '数据记录状态';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."CYKSBM" IS '出院科室编码';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."CYKSMC" IS '出院科室名称';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."ZYYSGH" IS '住院医生编号';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."ZYYSXM" IS '住院医生姓名';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."ZYYSSFZHM" IS '住院 医生身份证号码';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."SFLCLJ" IS '是否临床路径';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."LCLJLX" IS '临床路径类型';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."CYSJ" IS '出院时间';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."LCYXLXBM" IS '临床医学类型编码';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."RYQK" IS '入院情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."SQSHZDFHQK" IS '住院术前术后诊断符合情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."MZCYZDFHQK" IS '门诊出院诊断符合情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."RYCYZDFHQK" IS '入 院出院诊断符合情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."FSBLZDFHQK" IS '放射与病理诊断符合情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."BLJCLCZDFHQK" IS '病理检查与临床诊断符合情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."YYGRQK" IS '医院感染情况';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."GRBW" IS '感染部位';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."YYGRMC" IS '医院感染名称';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."QJCS" IS '抢救次数';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."QJCGCS" IS '抢救成功次数';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."LGBZ" IS '留观标志';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."BXLX" IS '保险类型';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."TXBZ" IS '特需标志';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_ZY_CYDJMXB"."YLYL2" IS '预留二';