DROP TABLE IF EXISTS "TB_XMCB_SR";
CREATE TABLE "TB_XMCB_SR" (
    "YLJGDM" varchar(33),
    "FID" varchar(75),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FSOURCESYS" varchar(30),
    "FDEPT" varchar(30),
    "FDEPTNAME" varchar(75),
    "FMEDPROJECTID" varchar(30),
    "FMEDPROJECTNAME" varchar(75),
    "FPRICE" numeric(18,8),
    "FAMOUT" numeric(18,8),
    "FWORKLOAD" numeric(18,8),
    "FUNIT" varchar(75),
    "FBDEPT" varchar(30),
    "FBDEPTNAME" varchar(75),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_XMCB_SR" IS '收入工作量中间表';
COMMENT ON COLUMN "TB_XMCB_SR"."YLJGDM" IS '医疗机构组代码';
COMMENT ON COLUMN "TB_XMCB_SR"."FID" IS '主键';
COMMENT ON COLUMN "TB_XMCB_SR"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_XMCB_SR"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_XMCB_SR"."FSOURCESYS" IS '数据来源';
COMMENT ON COLUMN "TB_XMCB_SR"."FDEPT" IS '源系统科室编码';
COMMENT ON COLUMN "TB_XMCB_SR"."FDEPTNAME" IS '源系统科室名称';
COMMENT ON COLUMN "TB_XMCB_SR"."FMEDPROJECTID" IS '来源医疗项目编码';
COMMENT ON COLUMN "TB_XMCB_SR"."FMEDPROJECTNAME" IS '来源医疗项目名称';
COMMENT ON COLUMN "TB_XMCB_SR"."FPRICE" IS '单价';
COMMENT ON COLUMN "TB_XMCB_SR"."FAMOUT" IS '金额';
COMMENT ON COLUMN "TB_XMCB_SR"."FWORKLOAD" IS '工作量';
COMMENT ON COLUMN "TB_XMCB_SR"."FUNIT" IS '单位';
COMMENT ON COLUMN "TB_XMCB_SR"."FBDEPT" IS '开单科室编码';
COMMENT ON COLUMN "TB_XMCB_SR"."FBDEPTNAME" IS '开单科室名称';
COMMENT ON COLUMN "TB_XMCB_SR"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_XMCB_SR"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_XMCB_SR"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_XMCB_SR"."YLYL2" IS '预留二';