DROP TABLE IF EXISTS "TB_CIS_RYPGJL";
CREATE TABLE "TB_CIS_RYPGJL" (
"YLJGDM" varchar(33),
"RYPGJLLSH" varchar(96),
"JZLSH" varchar(96),
"BRZSY" varchar(96),
"NLS" numeric,
"NLY" varchar(12),
"NLH" varchar(48),
"ZYH" varchar(27),
"KSMC" varchar(108),
"KSDM" varchar(54),
"BQMC" varchar(108),
"BFH" varchar(15),
"BCH" varchar(15),
"HZXM" varchar(108),
"XBDM" varchar(2),
"MZDM" varchar(3),
"MZMC" varchar(45),
"GJDM" varchar(5),
"GJMC" varchar(75),
"HYZKDM" varchar(3),
"HYZKMC" varchar(30),
"XLDM" varchar(3),
"XLMC" varchar(45),
"ZYLBDM" varchar(9),
"HZDHHM" varchar(30),
"HZDZYJDZ" varchar(105),
"LXRXM" varchar(108),
"LXRDHHM" varchar(30),
"RBFFS" varchar(15),
"RYZDBM" varchar(750),
"RYZDMC" varchar(1500),
"RYRQSJ" timestamp,
"ZYZZ" varchar(75),
"TW" numeric(4,1),
"SSY" numeric(3),
"SZY" numeric(3),
"TZ" numeric(6,2),
"HXPLC" numeric(3),
"MLC" numeric(3),
"RYYY" varchar(1500),
"RYTJDM" varchar(2),
"APGARPFZ" numeric(2),
"YSQKDM" varchar(2),
"FYCDDM" varchar(2),
"JSZTZCBZ" varchar(2),
"SMZK" varchar(1500),
"TSQK" varchar(1500),
"XLZTDM" varchar(2),
"YYZTDM" varchar(2),
"ZLNLDM" varchar(2),
"YBJKZKBZ" varchar(2),
"JBSHWS" varchar(1500),
"HZCRXBZ" varchar(2),
"CRBS" varchar(1500),
"YFJZS" varchar(1500),
"SSS" varchar(1500),
"SXS" varchar(1500),
"GMS" varchar(1500),
"JZS" varchar(1500),
"HLGCXMMC" varchar(300),
"HLGCJG" varchar(1500),
"XYBZ" varchar(2),
"TZXYTS" varchar(8),
"XYZKDM" varchar(2),
"RXYL" numeric(3),
"YJBZ" varchar(2),
"YJPLDM" varchar(1),
"RYJL" numeric(3),
"TZYSBZ" varchar(2),
"TZYSRQSJ" timestamp,
"PGRQSJ" timestamp,
"ZRHSXM" varchar(108),
"ZRHSGH" varchar(54),
"JZHSXM" varchar(108),
"JZHSGH" varchar(54),
"ZRHSQMRQSJ" timestamp,
"JZHSQMRQSJ" timestamp,
"BLSXSJ" timestamp,
"TBRQ" timestamp,
"XGBZ" varchar(2),
"YLYL1" varchar(192),
"YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_RYPGJL" IS '入院评估记录';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYPGJLLSH" IS '入院评估记录流水号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HZXM" IS '患者姓名';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XBDM" IS '性别代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."MZDM" IS '民族代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."MZMC" IS '民族名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."GJDM" IS '国籍代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."GJMC" IS '国籍名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HYZKDM" IS '婚姻状况代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HYZKMC" IS '婚姻状况名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XLDM" IS '学历代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XLMC" IS '学历名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZYLBDM" IS '职业类别代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HZDHHM" IS '患者电话号码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HZDZYJDZ" IS '患者电子邮件地址';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."LXRXM" IS '联系人姓名';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."LXRDHHM" IS '联系人电话号码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RBFFS" IS '入病房方式';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYZDBM" IS '入院诊断编码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYZDMC" IS '入院诊断名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYRQSJ" IS '入院日期时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZYZZ" IS '主要症状';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TW" IS '体温(℃)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."SSY" IS '收缩压（mmHg)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."SZY" IS '舒张压(mmHg)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TZ" IS '体重（kg)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HXPLC" IS '呼吸频率(次/min)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."MLC" IS '脉率(次/min)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYYY" IS '入院原因';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYTJDM" IS '入院途径代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."APGARPFZ" IS 'Apgar 评分值';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YSQKDM" IS '饮食情况代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."FYCDDM" IS '发育程度代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JSZTZCBZ" IS '精神状态正常标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."SMZK" IS '睡眠状况';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TSQK" IS '特殊情况';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XLZTDM" IS '心理状态代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YYZTDM" IS '营养状态代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZLNLDM" IS '自理能力代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YBJKZKBZ" IS '一般健康状况标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JBSHWS" IS '疾病史（含外伤）';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HZCRXBZ" IS '患者传染性标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."CRBS" IS '传染病史';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YFJZS" IS '预防接种史';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."SSS" IS '手术史';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."SXS" IS '输血史';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."GMS" IS '过敏史';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JZS" IS '家族史';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HLGCXMMC" IS '护理观察项目名称';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."HLGCJG" IS '护理观察结果';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XYBZ" IS '吸烟标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TZXYTS" IS '停止吸烟天数';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XYZKDM" IS '吸烟状况代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RXYL" IS '日吸烟量（支）';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YJBZ" IS '饮酒标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YJPLDM" IS '饮酒频率代码';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."RYJL" IS '日饮酒量（mL)';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TZYSBZ" IS '通知医师标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TZYSRQSJ" IS '通知医师日期时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."PGRQSJ" IS '评估日期时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZRHSXM" IS '责任护士姓名';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZRHSGH" IS '责任护士编号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JZHSXM" IS '接诊护士姓名';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JZHSGH" IS '接诊护士编号';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."ZRHSQMRQSJ" IS '责任护士签名日期时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."JZHSQMRQSJ" IS '接诊护士签名日期时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_RYPGJL"."YLYL2" IS '预留二';