DROP TABLE IF EXISTS "TB_XMCB_WSCL";
CREATE TABLE "TB_XMCB_WSCL" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "FSOURCESYS" varchar(30),
    "FDEPT" varchar(30),
    "FDEPTNAME" varchar(75),
    "FCOSTPROJECT" varchar(30),
    "FCOSTPROJECTNAME" varchar(75),
    "FMEDPROJECTID" varchar(30),
    "FMEDPROJECTNAME" varchar(75),
    "FPRICE" numeric(18,8),
    "FQTY" numeric(18,8),
    "FAMOUNT" numeric(18,8),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_XMCB_WSCL" IS '卫生材料明细表';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FID" IS '主键';
COMMENT ON COLUMN "TB_XMCB_WSCL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FSOURCESYS" IS '数据来源';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FDEPT" IS '源系统科室编码';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FDEPTNAME" IS '源系统科室名称';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FCOSTPROJECT" IS '成本项目编码';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FCOSTPROJECTNAME" IS '成本项目名称';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FMEDPROJECTID" IS '来源医疗项目编码';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FMEDPROJECTNAME" IS '来源医疗项目名称';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FPRICE" IS '单价';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FQTY" IS '数量';
COMMENT ON COLUMN "TB_XMCB_WSCL"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_XMCB_WSCL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_XMCB_WSCL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_XMCB_WSCL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_XMCB_WSCL"."YLYL2" IS '预留二';