DROP TABLE IF EXISTS "TB_CIS_JZLGBLJL";
CREATE TABLE "TB_CIS_JZLGBLJL" (
    "YLJGDM" varchar(33),
    "JZLGBLLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLXS" varchar(48),
    "JZRQSJ" timestamp,
    "CZBZDM" varchar(2),
    "SRGCSRQSJ" timestamp,
    "ZS" varchar(3000),
    "GMSBZ" varchar(2),
    "GMS" varchar(1500),
    "XBS" varchar(3000),
    "JWS" varchar(1500),
    "TGJC" varchar(750),
    "FZJCXM" varchar(1500),
    "FZJCJG" varchar(6000),
    "ZYSX" varchar(1500),
    "HZQXDM" varchar(2),
    "YSGH" varchar(54),
    "YSXM" varchar(108),
    "ZYSZGCJG" varchar(1500),
    "BZYJ" varchar(150),
    "ZZZF" varchar(150),
    "CBZD_XYZDBM" varchar(750),
    "CBZD_XYZDMC" varchar(1500),
    "CBZD_ZYBMDM" varchar(750),
    "CBZD_ZYB MMC" varchar(1500),
    "CBZD_ZYZHDM" varchar(750),
    "CBZD_ZYZHMC" varchar(1500),
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_JZLGBLJL" IS '急诊留观病历记录';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."JZLGBLLSH" IS '急诊留观病历流水号';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."NLXS" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."JZRQSJ" IS '就诊日期时间';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CZBZDM" IS '初诊标志代码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."SRGCSRQSJ" IS '收入观察室日期时间';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."ZS" IS '主诉';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."GMSBZ" IS '过敏史标志';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."GMS" IS '过敏史';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."XBS" IS '现病史';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."JWS" IS '既往史';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."TGJC" IS '体格检查';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."FZJCXM" IS '辅助检查项目';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."FZJCJG" IS '辅助检查结果';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."ZYSX" IS '注意事项';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."HZQXDM" IS '患者去向代码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."YSGH" IS '医师编号';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."YSXM" IS '医师姓名';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."ZYSZGCJG" IS '中医“ 四诊 ”观察结果';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."BZYJ" IS '辨证依据';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."ZZZF" IS '治则治法';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CBZD_XYZDBM" IS '初步诊断--西医诊断编码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CBZD_XYZDMC" IS '初步诊断--西医诊断名称';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CBZD_ZYBMDM" IS '初步诊断--中医病名代码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CBZD_ZYB MMC" IS '初步诊断--中医病名名称';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CBZD_ZYZHDM" IS '初步诊断--中医证候代码';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."CBZD_ZYZHMC" IS '初步诊断--中医证候名称';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_JZLGBLJL"."YLYL2" IS '预留二';