DROP TABLE IF EXISTS "TB_MZ_JSZFFSMXB";
CREATE TABLE "TB_MZ_JSZFFSMXB" (
    "YLJGDM" varchar(33),
    "ZFFSJLID" varchar(54),
    "BRZSY" varchar(96),
    "JZLSH" varchar(54),
    "JSJLID" varchar(54),
    "JLSFZT" varchar(2),
    "ZFFSDM" varchar(3),
    "ZFFSJE" numeric(10,4),
    "FYJSSJ" timestamp,
    "JSRYGH" varchar(54),
    "JSRYXM" varchar(108),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_MZ_JSZFFSMXB" IS '门诊结算支付方式明细表';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."ZFFSJLID" IS '支付方式记录 ID';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."JSJLID" IS '结算记录 ID';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."JLSFZT" IS '记录收费状态';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."ZFFSDM" IS '支付方式代码';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."ZFFSJE" IS '支付方式金额';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."FYJSSJ" IS '费用结算时间';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."JSRYGH" IS '结算人员编号';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."JSRYXM" IS '结算人员姓名';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_MZ_JSZFFSMXB"."YLYL2" IS '预留二';