DROP TABLE IF EXISTS "TB_BZCB_SSMZ";
CREATE TABLE "TB_BZCB_SSMZ" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FACCOUNTNO" varchar(75),
    "FOPEFLOWNUMBER" varchar(75),
    "FORDERDEPTID" varchar(255),
    "FOPEEXECDEPTID" varchar(255),
    "FPATIENTNAME" varchar(75),
    "FOPERATIONLEVEL" varchar(255),
    "FOPERATIONNUMBER" varchar(75),
    "FOPERATIONNAME" varchar(75),
    "FOPESTARTTIME" timestamp,
    "FOPEENDTIME" timestamp,
    "FOPEMINUTES" numeric,
    "FMAINOPEDOCTOR" varchar(383),
    "FOPEASSISTANT1" varchar(383),
    "FOPEASSISTANT2" varchar(383),
    "FOPEASSISTANT3" varchar(383),
    "FOPEASSISTANT4" varchar(383),
    "FANESTARTTIME" timestamp,
    "FANEENDTIME" timestamp,
    "FANEMINUTES" numeric,
    "FANESTHESIAWAY" varchar(75),
    "FANEEXECDEPTID" varchar(383),
    "FMAINANEDOCTOR" varchar(383),
    "FANEASSISTANT1" varchar(383),
    "FANEASSISTANT2" varchar(383),
    "FANEASSISTANT3" varchar(383),
    "FANEASSISTANT4" varchar(383),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_BZCB_SSMZ" IS '手术麻醉数据中间表';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FACCOUNTNO" IS '住院流水号';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEFLOWNUMBER" IS '手术流水号';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FORDERDEPTID" IS '开单科室编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEEXECDEPTID" IS '手术执行科室编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FPATIENTNAME" IS '患者姓名';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPERATIONLEVEL" IS '手术等级';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPERATIONNUMBER" IS '手术编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPERATIONNAME" IS '手术名称';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPESTARTTIME" IS '手术开始时间';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEENDTIME" IS '手术结束时间';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEMINUTES" IS '手术时长（分钟）';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FMAINOPEDOCTOR" IS '主刀医师编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEASSISTANT1" IS '手术助手 1 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEASSISTANT2" IS '手术助手 2 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEASSISTANT3" IS '手术助手 3 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FOPEASSISTANT4" IS '手术助手 4 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANESTARTTIME" IS '麻醉开始时间';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEENDTIME" IS '麻醉结束时间';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEMINUTES" IS '麻醉时长（分钟）';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANESTHESIAWAY" IS '麻醉方法';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEEXECDEPTID" IS '麻醉执行科室编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FMAINANEDOCTOR" IS '主麻医师编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEASSISTANT1" IS '麻醉助手 1 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEASSISTANT2" IS '麻醉助手 2 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEASSISTANT3" IS '麻醉助手 3 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."FANEASSISTANT4" IS '麻醉助手 4 编码';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_BZCB_SSMZ"."YLYL2" IS '预留二';