DROP TABLE IF EXISTS "TB_CIS_YNBLTL";
CREATE TABLE "TB_CIS_YNBLTL" (
    "YLJGDM" varchar(33),
    "YNBLLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "TLRQSJ" timestamp,
    "TLDD" varchar(750),
    "CJTLRYGHLB" varchar(300),
    "CJTLRYXMLB" varchar(300),
    "CJTLRYZYJSZWDM" varchar(30),
    "CJTLRYZYJSZWMC" varchar(192),
    "ZCRGH" varchar(54),
    "ZCRXM" varchar(108),
    "ZCRZYJSZW DM" varchar(2),
    "TLYJ" varchar(6000),
    "ZCRZJYJ" varchar(6000),
    "ZZYSXM" varchar(108),
    "ZZYSGH" varchar(54),
    "ZRYSXM" varchar(108),
    "ZRYSGH" varchar(54),
    "ZYSZGCJG" varchar(1500),
    "BZLZXXMS" varchar(3000),
    "ZYCFYZNR" varchar(1500),
    "ZYYYFF" varchar(150),
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_YNBLTL" IS '疑难病例讨论';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."YNBLLSH" IS '疑难病例讨论流水号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."TLRQSJ" IS '讨论日期时间';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."TLDD" IS '讨论地点';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."CJTLRYGHLB" IS '参加讨论人员工号列表';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."CJTLRYXMLB" IS '参加讨论人员姓名列表';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."CJTLRYZYJSZWDM" IS '参加讨论人员专业技术职务代码';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."CJTLRYZYJSZWMC" IS '参加讨论人员专业技术职务名称';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZCRGH" IS '主持人工号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZCRXM" IS '主持人姓名';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZCRZYJSZW DM" IS '主持人专业技术职务代码';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."TLYJ" IS '讨论意见';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZCRZJYJ" IS '主持人总结意见';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZZYSXM" IS '主治医师姓名';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZZYSGH" IS '主治医师编号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZRYSXM" IS '主任医师姓名';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZRYSGH" IS '主任医师编号';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZYSZGCJG" IS '中医“四诊”观察结果';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."BZLZXXMS" IS '辨证论治详细描述';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZYCFYZNR" IS '中药处方医嘱内容';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."ZYYYFF" IS '中药用药方法';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_YNBLTL"."YLYL2" IS '预留二';