DROP TABLE IF EXISTS "TB_CIS_MZSHFSJL";
CREATE TABLE "TB_CIS_MZSHFSJL" (
    "YLJGDM" varchar(33),
    "MZSHFSJLLSH" varchar(96),
    "MZZYBZ" varchar(2),
    "JZLSH" varchar(96),
    "MZZYH" varchar(27),
    "MZJLLSH" varchar(96),
    "DZSQDBH" varchar(30),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "TZ" numeric,
    "ABOXXDM" varchar(2),
    "RHXXDM" varchar(2),
    "SQZDBM" varchar(750),
    "SQZDMC" varchar(1500),
    "SHZDBM" varchar(750),
    "SHZDMC" varchar(1500),
    "YBZKJCJG" varchar(1500),
    "SSJCZBM" varchar(75),
    "SSJCZMC" varchar(120),
    "MZFFDM" varchar(30),
    "MZFFMC" varchar(150),
    "MZHFQK" varchar(150),
    "QXRQSJ" timestamp,
    "BCQGCGBZ" varchar(2),
    "TSQK" varchar(1500),
    "MZSYZ" varchar(150),
    "MZYSXM" varchar(108),
    "MZYSGH" varchar(54),
    "MZYSQMRQSJ" timestamp,
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_MZSHFSJL" IS '麻醉术后访视记录';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZSHFSJLLSH" IS '麻醉术后访视记录流水号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZZYBZ" IS '门诊/住院标志';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."JZLSH" IS '就诊流水号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZZYH" IS '门诊/住院号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZJLLSH" IS '麻醉记录流水号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."DZSQDBH" IS '电子申请单编号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."TZ" IS '体重';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."ABOXXDM" IS 'ABO 血型代码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."RHXXDM" IS 'Rh 血型代码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."SQZDBM" IS '术前诊断编码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."SQZDMC" IS '术前诊断名称';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."SHZDBM" IS '术后诊断编码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."SHZDMC" IS '术后诊断名称';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."YBZKJCJG" IS '一般状况检查结果';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."SSJCZBM" IS '手术及操作编码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."SSJCZMC" IS '手术及操作名称';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZFFDM" IS '麻醉方法代码';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZFFMC" IS '麻醉方法名称';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZHFQK" IS '麻醉恢复情况';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."QXRQSJ" IS '清醒日期时间';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."BCQGCGBZ" IS '拔除气管插管标志';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."TSQK" IS '特殊情况';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZSYZ" IS '麻醉适应证';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZYSXM" IS '麻醉医师姓名';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZYSGH" IS '麻醉医师编号';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."MZYSQMRQSJ" IS '麻醉医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_MZSHFSJL"."YLYL2" IS '预留二';