DROP TABLE IF EXISTS "TB_CIS_RCBCJL";
CREATE TABLE "TB_CIS_RCBCJL" (
    "YLJGDM" varchar(33),
    "RCBCJLLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "ZYBC" varchar(6000),
    "YZNR" varchar(1500),
    "ZZYSZYJSZWLBDM" varchar(2),
    "ZZYSXM" varchar(108),
    "ZZYSGH" varchar(54),
    "QMRQSJ" timestamp,
    "ZYSZGCJG" varchar(1500),
    "BZLZXXMS" varchar(3000),
    "ZYJZFF" varchar(150),
    "ZYYYFF" varchar(150),
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_RCBCJL" IS '日常病程记录';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."RCBCJLLSH" IS '日常病程记录流水号';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZYBC" IS '住院病程';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."YZNR" IS '医嘱内容';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZZYSZYJSZWLBDM" IS '主治医师专业技术职务类别代码';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZZYSXM" IS '主治医师姓名';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZZYSGH" IS '主治医师编号';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."QMRQSJ" IS '签名日期时间';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZYSZGCJG" IS '中医“四诊”观察结果';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."BZLZXXMS" IS '辨证论治详细描述';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZYJZFF" IS '中药煎煮方法';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."ZYYYFF" IS '中药用药方法';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_RCBCJL"."YLYL2" IS '预留二';