DROP TABLE IF EXISTS "TB_CIS_SWBLTLJL";
CREATE TABLE "TB_CIS_SWBLTLJL" (
    "YLJGDM" varchar(33),
    "SWBLTLJLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "TLRQSJ" timestamp,
    "TLDD" varchar(750),
    "ZCRXM" varchar(108),
    "ZCRGH" varchar(54),
    "ZCRZYJSZWDM" varchar(2),
    "ZCRZYJSZWMC" varchar(15),
    "CJTLRYGHLB" varchar(300),
    "CJTLRYXMLB" varchar(300),
    "CJZYJSZWLBDM" varchar(30),
    "CJTLRYZYJSZWMC" varchar(192),
    "ZJSWYYMC" varchar(768),
    "ZJSWYYBM" varchar(96),
    "SWZDBM" varchar(750),
    "SWZDMC" varchar(1500),
    "SWTLJL" varchar(6000),
    "ZCRZJYJ" varchar(3000),
    "ZZYSXM" varchar(108),
    "ZZYSGH" varchar(54),
    "ZRYSXM" varchar(108),
    "ZRYSGH" varchar(54),
    "ZYYSQMRQSJ" timestamp,
    "ZZYSQMRQSJ" timestamp,
    "ZRYSQMRQSJ" timestamp,
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_SWBLTLJL" IS '死亡病例讨论记录';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."SWBLTLJLSH" IS '死亡病例讨论记录流水号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."TLRQSJ" IS '讨论日期时间';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."TLDD" IS '讨论地点';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZCRXM" IS '主持人姓名';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZCRGH" IS '主持人工号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZCRZYJSZWDM" IS '主持人专业技术职务代码';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZCRZYJSZWMC" IS '主持人专业技术职务名称';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."CJTLRYGHLB" IS '参加讨论人员工列表';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."CJTLRYXMLB" IS '参加讨论人员姓列表';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."CJZYJSZWLBDM" IS '参加专业技术职务类别代码';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."CJTLRYZYJSZWMC" IS '参加讨论人员专业技术职务名称';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZJSWYYMC" IS '直接死亡原因名';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZJSWYYBM" IS '直接死亡原因编';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."SWZDBM" IS '死亡诊断编码';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."SWZDMC" IS '死亡诊断名称';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."SWTLJL" IS '死亡讨论记录';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZCRZJYJ" IS '主持人总结意见';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZZYSXM" IS '主治医师姓名';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZZYSGH" IS '主治医师编号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZRYSXM" IS '主任医师姓名';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZRYSGH" IS '主任医师编号';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZYYSQMRQSJ" IS '住院医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZZYSQMRQSJ" IS '主治医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."ZRYSQMRQSJ" IS '主任医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_SWBLTLJL"."YLYL2" IS '预留二';