DROP TABLE IF EXISTS "TB_BZCB_JR";
CREATE TABLE "TB_BZCB_JR" (
    "FID" varchar(75),
    "YLJGDM" varchar(33),
    "TJND" varchar(6),
    "TJYF" varchar(3),
    "FACCOUNTNO" varchar(75),
    "FOPEFLOWNUMBER" varchar(75),
    "FORDERDEPTID" varchar(383),
    "FEXECUTEDEPTID" varchar(383),
    "FORDERDATE" timestamp,
    "FEXECUTEDATE" timestamp,
    "FPATIENTNAME" varchar(75),
    "FAMOUNT" numeric(15,2),
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_BZCB_JR" IS '介入收入数据中间表';
COMMENT ON COLUMN "TB_BZCB_JR"."FID" IS '主键';
COMMENT ON COLUMN "TB_BZCB_JR"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_BZCB_JR"."TJND" IS '统计年度';
COMMENT ON COLUMN "TB_BZCB_JR"."TJYF" IS '统计月份';
COMMENT ON COLUMN "TB_BZCB_JR"."FACCOUNTNO" IS '住院流水号';
COMMENT ON COLUMN "TB_BZCB_JR"."FOPEFLOWNUMBER" IS '介入手术流水号';
COMMENT ON COLUMN "TB_BZCB_JR"."FORDERDEPTID" IS '开单科室编码';
COMMENT ON COLUMN "TB_BZCB_JR"."FEXECUTEDEPTID" IS '执行科室编码';
COMMENT ON COLUMN "TB_BZCB_JR"."FORDERDATE" IS '开单日期';
COMMENT ON COLUMN "TB_BZCB_JR"."FEXECUTEDATE" IS '执行日期';
COMMENT ON COLUMN "TB_BZCB_JR"."FPATIENTNAME" IS '患者姓名';
COMMENT ON COLUMN "TB_BZCB_JR"."FAMOUNT" IS '金额';
COMMENT ON COLUMN "TB_BZCB_JR"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_BZCB_JR"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_BZCB_JR"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_BZCB_JR"."YLYL2" IS '预留二';