DROP TABLE IF EXISTS "TB_CIS_SJYSCFJL";
CREATE TABLE "TB_CIS_SJYSCFJL" (
    "YLJGDM" varchar(33),
    "CFJLLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "KSMC" varchar(108),
    "KSDM" varchar(54),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "CFRQSJ" timestamp,
    "CFJL" varchar(6000),
    "YZNR" varchar(1500),
    "ZYSZGCJG" varchar(1500),
    "BZLZXXMS" varchar(3000),
    "ZYJZFF" varchar(150),
    "ZYYYFF" varchar(150),
    "ZLJH" varchar(3000),
    "ZLFAMS" varchar(3000),
    "ZZYSXM" varchar(108),
    "ZZYSGH" varchar(54),
    "ZRYSXM" varchar(108),
    "ZRYSGH" varchar(54),
    "ZZYSQMRQSJ" timestamp,
    "ZRYSQMRQSJ" timestamp,
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_SJYSCFJL" IS '上级医师查房记录';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."CFJLLSH" IS '上级医师查房记录流水号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."CFRQSJ" IS '查房日期时间';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."CFJL" IS '查房记录';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."YZNR" IS '医嘱内容';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZYSZGCJG" IS '中医“四诊”观察结果';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."BZLZXXMS" IS '辨证论治详细描述';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZYJZFF" IS '中药煎煮方法';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZYYYFF" IS '中药用药方法';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZLJH" IS '诊疗计划';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZLFAMS" IS '治疗方案描述';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZZYSXM" IS '主治医师姓名';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZZYSGH" IS '主治医师编号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZRYSXM" IS '主任医师姓名';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZRYSGH" IS '主任医师编号';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZZYSQMRQSJ" IS '主治医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."ZRYSQMRQSJ" IS '主任医师签名日期时间';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_SJYSCFJL"."YLYL2" IS '预留二';