DROP TABLE IF EXISTS "TB_CIS_SCBCJL";
CREATE TABLE "TB_CIS_SCBCJL" (
    "YLJGDM" varchar(33),
    "SCBCJLLSH" varchar(96),
    "JZLSH" varchar(96),
    "ZYH" varchar(27),
    "BRZSY" varchar(96),
    "NLS" numeric,
    "NLY" varchar(12),
    "NLH" varchar(48),
    "KSDM" varchar(54),
    "KSMC" varchar(108),
    "BQMC" varchar(108),
    "BFH" varchar(15),
    "BCH" varchar(15),
    "ZS" varchar(6000),
    "BLTD" varchar(6000),
    "ZDYJ" varchar(6000),
    "ZLJH" varchar(6000),
    "ZLFAMS" varchar(6000),
    "ZYYSXM" varchar(108),
    "ZYYSGH" varchar(54),
    "SJYSXM" varchar(108),
    "SJYSGH" varchar(54),
    "ZYSZGCJG" varchar(1500),
    "BZLZXXMS" varchar(1500),
    "ZZZF" varchar(150),
    "CBZD_XYZDBM" varchar(750),
    "CBZD_XYZDMC" varchar(1500),
    "CBZD_ZYBMDM" varchar(750),
    "CBZD_ZYBMMC" varchar(1500),
    "CBZD_ZYZHDM" varchar(750),
    "CBZD_ZYZHMC" varchar(1500),
    "JBZD_XYZDBM" varchar(750),
    "JBZD_XYZDMC" varchar(1500),
    "JBZD_ZYBMDM" varchar(750),
    "JBZD_ZYBMMC" varchar(1500),
    "JBZD_ZYZHDM" varchar(750),
    "JBZD_ZYZHMC" varchar(1500),
    "BLSXSJ" timestamp,
    "TBRQ" timestamp,
    "XGBZ" varchar(2),
    "YLYL1" varchar(192),
    "YLYL2" varchar(192)
);
COMMENT ON TABLE "TB_CIS_SCBCJL" IS '首次病程记录';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."YLJGDM" IS '医疗机构代码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."SCBCJLLSH" IS '首次病程记录流水号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JZLSH" IS '住院就诊流水号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZYH" IS '住院号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BRZSY" IS '患者主索引';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."NLS" IS '年龄（岁）';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."NLY" IS '年龄（月）';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."NLH" IS '年龄（小时）';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."KSDM" IS '科室代码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."KSMC" IS '科室名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BQMC" IS '病区名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BFH" IS '病房号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BCH" IS '病床号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZS" IS '主诉';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BLTD" IS '病例特点';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZDYJ" IS '诊断依据';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZLJH" IS '诊疗计划';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZLFAMS" IS '治疗方案描述';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZYYSXM" IS '住院医师姓名';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZYYSGH" IS '住院医师编号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."SJYSXM" IS '上级医师姓名';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."SJYSGH" IS '上级医师编号';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZYSZGCJG" IS '中医“四诊”观察结果';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BZLZXXMS" IS '辨证论治详细描述';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."ZZZF" IS '治则治法';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."CBZD_XYZDBM" IS '初步诊断-西医诊断编码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."CBZD_XYZDMC" IS '初步诊断-西医诊断名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."CBZD_ZYBMDM" IS '初步诊断-中医病名代码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."CBZD_ZYBMMC" IS '初步诊断-中医病名名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."CBZD_ZYZHDM" IS '初步诊断-中医证候代码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."CBZD_ZYZHMC" IS '初步诊断-中医证候名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JBZD_XYZDBM" IS '鉴别诊断-西医诊断编码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JBZD_XYZDMC" IS '鉴别诊断-西医诊断名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JBZD_ZYBMDM" IS '鉴别诊断-中医病名代码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JBZD_ZYBMMC" IS '鉴别诊断-中医病名名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JBZD_ZYZHDM" IS '鉴别诊断-中医证候代码';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."JBZD_ZYZHMC" IS '鉴别诊断-中医证候名称';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."BLSXSJ" IS '病历书写时间';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."TBRQ" IS '数据上传时间';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."XGBZ" IS '修改标志';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."YLYL1" IS '预留一';
COMMENT ON COLUMN "TB_CIS_SCBCJL"."YLYL2" IS '预留二';