"""Add departments table

Revision ID: 0d2bb5cf1133
Revises: b1cd20417f09
Create Date: 2025-10-22 10:20:18.291121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2bb5cf1133'
down_revision = 'b1cd20417f09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('his_code', sa.String(length=50), nullable=False, comment='HIS科室代码'),
    sa.Column('his_name', sa.String(length=100), nullable=False, comment='HIS科室名称'),
    sa.Column('cost_center_code', sa.String(length=50), nullable=True, comment='成本中心代码'),
    sa.Column('cost_center_name', sa.String(length=100), nullable=True, comment='成本中心名称'),
    sa.Column('accounting_unit_code', sa.String(length=50), nullable=True, comment='核算单元代码'),
    sa.Column('accounting_unit_name', sa.String(length=100), nullable=True, comment='核算单元名称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否参与评估'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_his_code'), 'departments', ['his_code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_his_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
