"""Initial migration: users, roles, permissions

Revision ID: b1cd20417f09
Revises: 33b1cc715d32
Create Date: 2025-10-21 18:34:33.734289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1cd20417f09'
down_revision = '33b1cc715d32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
