"""Add sort_order to departments

Revision ID: e6c2a4774ba8
Revises: 0d2bb5cf1133
Create Date: 2025-10-22 10:47:19.537920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c2a4774ba8'
down_revision = '0d2bb5cf1133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可为空的列
    op.add_column('departments', sa.Column('sort_order', sa.Numeric(precision=10, scale=2), nullable=True, comment='排序序号'))
    
    # 为现有数据设置默认值（按ID顺序）
    op.execute("""
        UPDATE departments 
        SET sort_order = id 
        WHERE sort_order IS NULL
    """)
    
    # 将列改为不可为空
    op.alter_column('departments', 'sort_order', nullable=False)
    
    # 创建索引
    op.create_index(op.f('ix_departments_sort_order'), 'departments', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_sort_order'), table_name='departments')
    op.drop_column('departments', 'sort_order')
    # ### end Alembic commands ###
