"""Add charge_items and dimension_item_mappings tables

Revision ID: f0384ea4c792
Revises: e6c2a4774ba8
Create Date: 2025-10-22 11:27:04.681964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0384ea4c792'
down_revision = 'e6c2a4774ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False, comment='收费项目编码'),
    sa.Column('item_name', sa.String(length=255), nullable=False, comment='收费项目名称'),
    sa.Column('item_category', sa.String(length=100), nullable=True, comment='收费项目分类'),
    sa.Column('unit_price', sa.String(length=50), nullable=True, comment='单价'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_items_id'), 'charge_items', ['id'], unique=False)
    op.create_index(op.f('ix_charge_items_item_code'), 'charge_items', ['item_code'], unique=True)
    op.create_table('dimension_item_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False, comment='维度节点ID'),
    sa.Column('item_code', sa.String(length=100), nullable=False, comment='收费项目编码'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_item_mappings_dimension_id'), 'dimension_item_mappings', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_dimension_item_mappings_id'), 'dimension_item_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_dimension_item_mappings_item_code'), 'dimension_item_mappings', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimension_item_mappings_item_code'), table_name='dimension_item_mappings')
    op.drop_index(op.f('ix_dimension_item_mappings_id'), table_name='dimension_item_mappings')
    op.drop_index(op.f('ix_dimension_item_mappings_dimension_id'), table_name='dimension_item_mappings')
    op.drop_table('dimension_item_mappings')
    op.drop_index(op.f('ix_charge_items_item_code'), table_name='charge_items')
    op.drop_index(op.f('ix_charge_items_id'), table_name='charge_items')
    op.drop_table('charge_items')
    # ### end Alembic commands ###
